=== luciomdp/Proyecto_final/torneo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT torneo (equipos, arbitros)>
<!ELEMENT equipos (equipo+)> 
<!ELEMENT equipo (nombre, pais, ranking, plantel)> 
<!ELEMENT plantel (jugadores, dt+)> 
<!ELEMENT jugadores (jugador+)> 
<!ELEMENT jugador (persona)> 
<!ELEMENT dt (persona, pais, titulosObtenidos)> 
<!ELEMENT arbitros (arbitro*)> 
<!ELEMENT arbitro (persona, pais, aniosReferato)> 
<!ELEMENT persona (tipoDocumento, nroDocumento, nombre, fechaNacimiento)> 
<!ELEMENT tipoDocumento (#PCDATA)>
<!ELEMENT nroDocumento (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fechaNacimiento (#PCDATA)>
<!ELEMENT puntuacion (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT aniosReferato (#PCDATA)>
<!ELEMENT titulosObtenidos (#PCDATA)>
<!ELEMENT ranking (#PCDATA)>
<!ATTLIST jugador posicion (arquero | defensor | mediocampista | delantero) #REQUIRED puntuacion (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10) #REQUIRED>

=== luciomdp/Proyecto_final/torneo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE torneo SYSTEM "torneo.dtd">
<torneo>
  <equipos>
    <equipo>
      <nombre>Lonabarce</nombre>
      <pais>Hispania</pais>
      <ranking>4</ranking>
      <plantel>
        <jugadores>
          <jugador posicion="arquero" puntuacion="8">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>1234</nroDocumento>
              <nombre>Mangalarga Juan</nombre>
              <fechaNacimiento>30/11/1985</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="arquero"  puntuacion="4">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>8564</nroDocumento>
              <nombre>Noagarrauna Pedro</nombre>
              <fechaNacimiento>30/03/1985</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="6">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>5678</nroDocumento>
              <nombre>Quebracho Anibal</nombre>
              <fechaNacimiento>30/11/1995</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="8">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>5678</nroDocumento>
              <nombre>Nopasaras Daniel</nombre>
              <fechaNacimiento>30/11/1999</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="7">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>6527</nroDocumento>
              <nombre>Rompemedias Jose</nombre>
              <fechaNacimiento>01/11/1999</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="3">
            <persona>
              <tipoDocumento>PAS</tipoDocumento>
              <nroDocumento>9687</nroDocumento>
              <nombre>Lentissimo Massimo</nombre>
              <fechaNacimiento>30/11/2005</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="9">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>2347</nroDocumento>
              <nombre>Fortachon Abel</nombre>
              <fechaNacimiento>30/11/2000</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="7">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>9673</nroDocumento>
              <nombre>Impassable Gino</nombre>
              <fechaNacimiento>17/02/1996</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="mediocampista" puntuacion="4">
            <persona>
              <tipoDocumento>PAS</tipoDocumento>
              <nroDocumento>8791</nroDocumento>
              <nombre>Immobile Sergei</nombre>
              <fechaNacimiento>17/05/1994</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="mediocampista" puntuacion="9">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>6270</nroDocumento>
              <nombre>HerMotor Ludwig</nombre>
              <fechaNacimiento>31/05/1994</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="mediocampista" puntuacion="8">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>1065</nroDocumento>
              <nombre>Gambetita Guido</nombre>
              <fechaNacimiento>31/08/1994</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="mediocampista" puntuacion="5">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>1065</nroDocumento>
              <nombre>Hachabrava Fernando</nombre>
              <fechaNacimiento>31/01/1998</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="mediocampista" puntuacion="7">
            <persona>
              <tipoDocumento>PAS</tipoDocumento>
              <nroDocumento>6064</nroDocumento>
              <nombre>Redcard Jimmy</nombre>
              <fechaNacimiento>31/01/1998</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="delantero" puntuacion="9">
            <persona>
              <tipoDocumento>PAS</tipoDocumento>
              <nroDocumento>8084</nroDocumento>
              <nombre>Laemboca Mutombo</nombre>
              <fechaNacimiento>31/03/1994</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="delantero" puntuacion="10">
            <persona>
              <tipoDocumento>PAS</tipoDocumento>
              <nroDocumento>4235</nroDocumento>
              <nombre>Tanker Gerrard</nombre>
              <fechaNacimiento>31/03/1994</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="delantero" puntuacion="9">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>3018</nroDocumento>
              <nombre>Golito Pedro</nombre>
              <fechaNacimiento>01/03/1994</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="delantero" puntuacion="9">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>3717</nroDocumento>
              <nombre>Palomito Lucio</nombre>
              <fechaNacimiento>01/03/1985</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="delantero" puntuacion="9">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>2879</nroDocumento>
              <nombre>Golentra Ettore</nombre>
              <fechaNacimiento>01/03/2001</fechaNacimiento>
            </persona>
          </jugador>
        </jugadores>
        <dt>
          <persona>
            <tipoDocumento>DU</tipoDocumento>
            <nroDocumento>9687</nroDocumento>
            <nombre>Orchestra Luigi</nombre>
            <fechaNacimiento>06/06/2005</fechaNacimiento>
          </persona>
          <pais>Italica</pais>
          <titulosObtenidos>15</titulosObtenidos>
        </dt>
      </plantel>
    </equipo>
    <equipo>
      <nombre>Perrissimos</nombre>
      <pais>Italica</pais>
      <ranking>98</ranking>
      <plantel>
        <jugadores>
          <jugador posicion="arquero" puntuacion="3">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>11111</nroDocumento>
              <nombre>Agujeretti Lino</nombre>
              <fechaNacimiento>30/11/1985</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="arquero"  puntuacion="2">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>22222</nroDocumento>
              <nombre>Sinmanno Renzo</nombre>
              <fechaNacimiento>30/03/1985</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="4">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>33333</nroDocumento>
              <nombre>Lastimosso Victor</nombre>
              <fechaNacimiento>30/11/1995</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="2">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>44444</nroDocumento>
              <nombre>Accalambra Dino</nombre>
              <fechaNacimiento>30/11/1999</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="4">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>55555</nroDocumento>
              <nombre>Nullo Giussepe</nombre>
              <fechaNacimiento>01/11/1999</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="5">
            <persona>
              <tipoDocumento>PAS</tipoDocumento>
              <nroDocumento>66666</nroDocumento>
              <nombre>Tragaterra Lucio</nombre>
              <fechaNacimiento>30/11/2005</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="4">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>77777</nroDocumento>
              <nombre>Horripile Genaro</nombre>
              <fechaNacimiento>30/11/2000</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="3">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>88888</nroDocumento>
              <nombre>Dessanimo Elisseo</nombre>
              <fechaNacimiento>17/02/1996</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="mediocampista" puntuacion="2">
            <persona>
              <tipoDocumento>PAS</tipoDocumento>
              <nroDocumento>99999</nroDocumento>
              <nombre>Disastroso Silvio</nombre>
              <fechaNacimiento>17/05/1994</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="mediocampista" puntuacion="1">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
